### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MerelvStekelenburg**
Wrote a short purpose and motivation, added the research question and preliminary list of characteristics, repository overview, and main contributors. The "example of reproducible research workflow" is still included in the README as it might be useful.

### CODE REVIEW

**Comment by Ana042** [comment]
I think you didn't include the review scores among the characteristics variables

**Comment by MerelvStekelenburg** [comment]
> 

I didn't include them (at least not yet) because there still listed as optional independent variables in the list

**Comment by alebock** [comment]
> I didn't include them (at least not yet) because they are still listed as optional independent variables in the list

>> I think we should include them since they don't require any sophisticated manipulation cause they are all numeric and they are characteristics of the listing, right?

**Comment by MerelvStekelenburg** [comment]
> > I didn't include them (at least not yet) because they are still listed as optional independent variables in the list
> 
> > > I think we should include them since they don't require any sophisticated manipulation cause they are all numeric and they are characteristics of the listing, right?

Okay, good idea. Do we want to include all review-related variables listed as optional or only review scores?

**Comment by Ana042** [comment]
> eview-related variables listed as optional or only review score

i would say only review scores

**Pull request merged**
